# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_concatenation.cc concatenation.cc -o concatenation

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f concatenation