# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g binary_to_decimal.cc -o binary_to_decimal

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f binary_to_decimal