# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g harmonic_numbers_1.cc -o harmonic_numbers_1

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f harmonic_numbers_1