# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g function_example.cc -o function_example

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f function_example