# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g uppercase_and_lowercase_letters.cc -o uppercase_and_lowercase_letters

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f uppercase_and_lowercase_letters