# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g polynomial.cc main_polynomial.cc -o polynomial

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f polynomial