# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g approximate_root.cc hypotenuse.cc -o hypotenuse

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f hypotenuse