# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g hypotenuse.cc approximate_root.h -o hypotenuse

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f hypotenuse