# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g add_one_second.cc -o add_one_second

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f add_one_second