# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_compute_int.cc compute_int.cc -o compute_int

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f compute_int