# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g approximate_root.cc -o approximate_root

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f approximate_root