# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g sum_of_digits.cc -o sum_of_digits

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f sum_of_digits