# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g random_numbers.cc -o random_numbers

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f random_numbers