# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g scalar_product.cc -o scalar_product

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f scalar_product