# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g maximum_of_three_integer_numbers.cc -o maximum_of_three_integer_numbers

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f maximum_of_three_integer_numbers