# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g numbers_in_an_interval.cc -o numbers_in_an_interval

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f numbers_in_an_interval