# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g vowels_and_consonant.cc -o vowels_and_consonant

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f vowels_and_consonant