# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g floating_point_arithmetics.cc -o floating_point_arithmetics

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f floating_point_arithmetics