# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_racional.cc racional.cc -o racionales

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f racionales