# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g capitalize_vowels.cc capitalize_vowels.h -o capitalize_vowels

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f capitalize_vowels