# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_complejo.cc complejo.cc -o complejo

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f complejo