# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g triangle_area.cc -o triangle_area

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f triangle_area