# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g decimal_to_binary.cc -o decimal_to_binary

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f decimal_to_binary